kind: pipeline
type: docker
name: deploy-dback

steps:
- name: iterprod
  image: docker:19.03  
  environment:
    DBACK_DOCKER_LOGIN:
      from_secret: DBACK_DOCKER_LOGIN
    DBACK_DOCKER_PASSWORD:
      from_secret: DBACK_DOCKER_PASSWORD
  volumes:
  - name: dockersocket
    path: /var/run/docker.sock
  commands:
    - apk update
    - apk add npm
    - npm run iterprod
volumes:
- name: dockersocket
  host:
    path: /var/run/docker.sock