kind: pipeline
name: build-dback

trigger:
  branch: master
  event: push

steps:
- name: build-dback
  image: docker:19.03
  volumes:
  - name: dockersocket
    path: /var/run/docker.sock
  commands:
  - apk update
  - apk add npm
  - npm i
  - "DBACK_DOCKER_LOGIN=$DBACK_DOCKER_LOGIN && DBACK_DOCKER_PASSWORD=$DBACK_DOCKER_PASSWORD && DBACK_DOCKER_REPO=$DBACK_DOCKER_REPO && npm run iterprod"
  secrets: [ DBACK_DOCKER_LOGIN, DBACK_DOCKER_PASSWORD, DBACK_DOCKER_REPO ]
volumes:
- name: dockersocket
  host:
    path: /var/run/docker.sock