FROM golang:1.13.7-alpine3.11 as build
RUN apk update && apk add build-base upx 
COPY go-app/src /go/src
ENV CGO_ENABLED=0
RUN cd /go/src/dback && go build -a -installsuffix cgo

FROM scratch as dev
COPY --from=build /go/src/dback/dback /bin/dback

ENV DOCKER_API_VERSION 1.37
ENTRYPOINT ["/bin/dback"]