cd %~dp0\..
set REPO=%cd%
set GOPATH=%cd%\..\..\..\..\
set GOROOT=%cd%\node_modules\go-win
set PATH=%PATH%;%GOPATH%\bin
set PATH=%PATH%;%GOROOT%\bin
set PATH=%PATH%;%REPO%\node_modules\liteide\bin
set PATH=%PATH%;%REPO%\node_modules\.bin
set PATH=%PATH%;%REPO%\scripts
set PATH=%PATH%;%REPO%\examples\websocket\scripts